# Generated by Django 6.0.2 on 2026-02-11 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(help_text='ElevenLabs agent ID', max_length=100, unique=True)),
                ('label', models.CharField(help_text="Friendly name, e.g. 'Tony's Pizzeria'", max_length=200)),
                ('elevenlabs_api_key', models.CharField(help_text="API key for this agent's workspace", max_length=200)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for this prompt version', max_length=200)),
                ('content', models.TextField(help_text='The full system prompt text')),
                ('is_active', models.BooleanField(default=False, help_text='Only one can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevenlabs_id', models.CharField(help_text='ElevenLabs conversation ID', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='unassigned', max_length=20)),
                ('call_duration_secs', models.IntegerField(blank=True, null=True)),
                ('call_timestamp', models.DateTimeField(blank=True, help_text='When the call started', null=True)),
                ('has_audio', models.BooleanField(default=False)),
                ('audio_s3_key', models.CharField(blank=True, default='', max_length=500)),
                ('user_audio_s3_key', models.CharField(blank=True, default='', max_length=500)),
                ('agent_audio_s3_key', models.CharField(blank=True, default='', max_length=500)),
                ('raw_data', models.JSONField(default=dict, help_text='Full raw response from ElevenLabs API')),
                ('annotator_notes', models.TextField(blank=True, default='')),
                ('reviewer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='conversations.agent')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-call_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Order within conversation, 0-indexed')),
                ('role', models.CharField(choices=[('user', 'Customer'), ('agent', 'Restaurant AI')], max_length=10)),
                ('original_text', models.TextField(help_text='Original transcript text from ElevenLabs')),
                ('edited_text', models.TextField(blank=True, default='', help_text="Annotator's edited version")),
                ('time_in_call_secs', models.FloatField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='conversations.conversation')),
            ],
            options={
                'ordering': ['conversation', 'position'],
                'unique_together': {('conversation', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('original_args', models.JSONField(default=dict, help_text='Original arguments from the LLM')),
                ('edited_args', models.JSONField(blank=True, default=dict, help_text="Annotator's corrected arguments")),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict, help_text='Response from the webhook')),
                ('error_message', models.TextField(blank=True, default='')),
                ('is_edited', models.BooleanField(default=False)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='conversations.turn')),
            ],
        ),
    ]
