# Generated by Django 6.0.2 on 2026-02-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_tag_toolcall_is_deleted_turn_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='rag_context',
            field=models.JSONField(blank=True, default=list, help_text='RAG chunks retrieved for this turn: [{document_id, chunk_id, content, vector_distance}]'),
        ),
    ]
